export * from "./analytics/index";
export * from "./applications/index";
export * from "./catalog/index";
export * from "./courses/index";
export * from "./guidance/index";
export * from "./intakes/index";
export * from "./students/index";
export * from "./universities/index";
export * from "./shared/index";
