-- Shared countries lookup table (public) replacing public.education_countries references.

CREATE TABLE IF NOT EXISTS public.countries (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  currency text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT countries_name_key UNIQUE (name)
);

CREATE INDEX IF NOT EXISTS countries_name_idx ON public.countries (name);

CREATE OR REPLACE FUNCTION public.countries_set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS countries_updated_at ON public.countries;
CREATE TRIGGER countries_updated_at
  BEFORE UPDATE ON public.countries
  FOR EACH ROW EXECUTE FUNCTION public.countries_set_updated_at();

-- Backfill shared countries from legacy table when present.
DO $$
BEGIN
  IF to_regclass('public.education_countries') IS NULL THEN
    RETURN;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'education_countries'
      AND column_name = 'currency'
  ) THEN
    INSERT INTO public.countries (name, currency)
    SELECT DISTINCT
      trim(ec.name),
      COALESCE(NULLIF(trim(ec.currency), ''), 'UNKNOWN')
    FROM public.education_countries ec
    WHERE trim(ec.name) <> ''
    ON CONFLICT (name) DO NOTHING;
  ELSE
    INSERT INTO public.countries (name, currency)
    SELECT DISTINCT
      trim(ec.name),
      'UNKNOWN'
    FROM public.education_countries ec
    WHERE trim(ec.name) <> ''
    ON CONFLICT (name) DO NOTHING;
  END IF;
END;
$$;

-- ---------------------------------------------------------------------------
-- app_users.country_id: uuid -> integer (nullable)
-- ---------------------------------------------------------------------------

ALTER TABLE public.app_users
  ADD COLUMN IF NOT EXISTS country_id_new integer;

UPDATE public.app_users au
SET country_id_new = c.id
FROM public.education_countries ec
JOIN public.countries c ON c.name = ec.name
WHERE au.country_id = ec.id;

ALTER TABLE public.app_users
  DROP CONSTRAINT IF EXISTS app_users_country_id_fkey;

DROP INDEX IF EXISTS app_users_country_id_idx;

ALTER TABLE public.app_users
  DROP COLUMN IF EXISTS country_id;

ALTER TABLE public.app_users
  RENAME COLUMN country_id_new TO country_id;

ALTER TABLE public.app_users
  ADD CONSTRAINT app_users_country_id_fkey
  FOREIGN KEY (country_id) REFERENCES public.countries (id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS app_users_country_id_idx ON public.app_users (country_id);

-- ---------------------------------------------------------------------------
-- education_module.universities.country_id: uuid -> integer (required)
-- ---------------------------------------------------------------------------

ALTER TABLE education_module.universities
  ADD COLUMN IF NOT EXISTS country_id_new integer;

UPDATE education_module.universities u
SET country_id_new = c.id
FROM public.education_countries ec
JOIN public.countries c ON c.name = ec.name
WHERE u.country_id = ec.id;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM education_module.universities
    WHERE country_id_new IS NULL
  ) THEN
    RAISE EXCEPTION 'Cannot migrate education_module.universities.country_id: some rows are not mapped to public.countries';
  END IF;
END;
$$;

ALTER TABLE education_module.universities
  DROP CONSTRAINT IF EXISTS universities_country_id_fkey;

DROP INDEX IF EXISTS education_module_universities_country_idx;

ALTER TABLE education_module.universities
  DROP COLUMN IF EXISTS country_id;

ALTER TABLE education_module.universities
  RENAME COLUMN country_id_new TO country_id;

ALTER TABLE education_module.universities
  ALTER COLUMN country_id SET NOT NULL;

ALTER TABLE education_module.universities
  ADD CONSTRAINT universities_country_id_fkey
  FOREIGN KEY (country_id) REFERENCES public.countries (id) ON DELETE RESTRICT;

CREATE INDEX IF NOT EXISTS education_module_universities_country_idx
  ON education_module.universities (country_id);

-- ---------------------------------------------------------------------------
-- education_module.visa_checklists.country_id: uuid -> integer (required)
-- ---------------------------------------------------------------------------

ALTER TABLE education_module.visa_checklists
  ADD COLUMN IF NOT EXISTS country_id_new integer;

UPDATE education_module.visa_checklists vc
SET country_id_new = c.id
FROM public.education_countries ec
JOIN public.countries c ON c.name = ec.name
WHERE vc.country_id = ec.id;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM education_module.visa_checklists
    WHERE country_id_new IS NULL
  ) THEN
    RAISE EXCEPTION 'Cannot migrate education_module.visa_checklists.country_id: some rows are not mapped to public.countries';
  END IF;
END;
$$;

ALTER TABLE education_module.visa_checklists
  DROP CONSTRAINT IF EXISTS visa_checklists_country_id_fkey;

DROP INDEX IF EXISTS education_module_visa_country_idx;

ALTER TABLE education_module.visa_checklists
  DROP COLUMN IF EXISTS country_id;

ALTER TABLE education_module.visa_checklists
  RENAME COLUMN country_id_new TO country_id;

ALTER TABLE education_module.visa_checklists
  ALTER COLUMN country_id SET NOT NULL;

ALTER TABLE education_module.visa_checklists
  ADD CONSTRAINT visa_checklists_country_id_fkey
  FOREIGN KEY (country_id) REFERENCES public.countries (id) ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS education_module_visa_country_idx
  ON education_module.visa_checklists (country_id);

-- Legacy table is no longer needed after all foreign keys are moved.
DROP TABLE IF EXISTS public.education_countries;
